# Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# zlug
source $HOME/.zplug/init.zsh

zplug "esc/conda-zsh-completion"
zplug "peterhurford/up.zsh"
zplug "lukechilds/zsh-nvm"

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

# Customize

alias info='info --vi-keys'
alias em='emacs -nw'
alias vi=em
alias vim='nvim'
alias vimdiff='nvim -d'
alias tig='tig --all'
alias bc='bc -l'
alias def='ydcv'
alias coin='coinmon -c jpy'
alias open='xdg-open'
alias dstat='dstat -am'
alias sl=ls
alias iv=vi
alias say=espeak
alias matrix='cmatrix -ab -u 3'
alias tmux='tmux -2'
alias vm='vmstat -t -S M 1'

export KEYTIMEOUT=1
export EDITOR='nvim'
export VISUAL='nvim'
export BROWSER="ccopy"
bindkey -M viins '^?' backward-delete-char
bindkey -M viins '^U' backward-kill-line
bindkey -M viins '^K' kill-whole-line
bindkey -M viins '^W' backward-delete-word
bindkey -M vicmd '^V' edit-command-line
bindkey -M emacs '^V' edit-command-line

wttr()
{
    # change Paris to your default location
    local request="wttr.in/${1-kashiwara}"
    request+='?qAF&lang=zh'
    [ "$COLUMNS" -lt 125 ] && request+='&n'
    curl --compressed "$request"
}

PATH=$PATH:$HOME/.local/bin

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/tinunkai/google-cloud-sdk/path.zsh.inc' ]; then . '/home/tinunkai/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/tinunkai/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/tinunkai/google-cloud-sdk/completion.zsh.inc'; fi

source ~/miniconda3/bin/activate
